*&---------------------------------------------------------------------*
*& Report  ZNAV_4_1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZNAV_4_1 MESSAGE-ID ZM1.
TABLES: TCURC.
PARAMETERS: P_CURR LIKE SFLIGHT-CURRENCY.
TYPES: BEGIN OF TY_SFLIGHT,
         CARRID   LIKE SFLIGHT-CARRID,
         CURRENCY LIKE SFLIGHT-CURRENCY,
         SALES    LIKE SFLIGHT-PAYMENTSUM,
         CONVCURR LIKE SFLIGHT-PAYMENTSUM,
       END OF TY_SFLIGHT.
DATA: I_FLT type  TCURC,
      I_SFLIGHT  TYPE STANDARD TABLE OF TY_SFLIGHT WITH NON-UNIQUE KEY carrid INITIAL SIZE 0,
      WA_SFLIGHT TYPE TY_SFLIGHT,
      SCARR-CARRNAME LIKE SCARR-CARRNAME.

AT SELECTION-SCREEN.
  SELECT SINGLE * FROM TCURC INTO I_FLT WHERE WAERS = P_CURR.
  IF SY-SUBRC <> 0.
    MESSAGE E001 WITH 'This currency is invalid'.
  ENDIF.

START-OF-SELECTION.
  SELECT DISTINCT CARRID CURRENCY FROM SFLIGHT INTO TABLE I_SFLIGHT.
  LOOP AT I_SFLIGHT INTO WA_SFLIGHT.
    SELECT SUM( PAYMENTSUM ) FROM SFLIGHT INTO WA_SFLIGHT-SALES WHERE CARRID = WA_SFLIGHT-CARRID.
    MODIFY I_SFLIGHT FROM WA_SFLIGHT.
  ENDLOOP.

  LOOP AT I_SFLIGHT INTO WA_SFLIGHT.
    CALL FUNCTION 'CONVERT_TO_LOCAL_CURRENCY'
      EXPORTING
        DATE             = SY-DATUM
        FOREIGN_AMOUNT   = WA_SFLIGHT-SALES
        FOREIGN_CURRENCY = WA_SFLIGHT-CURRENCY
        LOCAL_CURRENCY   = P_CURR
      IMPORTING
        LOCAL_AMOUNT     = WA_SFLIGHT-CONVCURR.
    IF SY-SUBRC <> 0.
      MESSAGE E001 WITH 'NO proper return from Function Module'.
    ENDIF.
    MODIFY I_SFLIGHT FROM WA_SFLIGHT.
*    WRITE:/ WA_SFLIGHT-CARRID, WA_SFLIGHT-CURRENCY, WA_SFLIGHT-SALES, WA_SFLIGHT-CONVCURR.
  ENDLOOP.

  SORT I_SFLIGHT BY CONVCURR DESCENDING.
  LOOP AT I_SFLIGHT INTO WA_SFLIGHT.
    SELECT SINGLE CARRNAME FROM SCARR INTO SCARR-CARRNAME WHERE CARRID = WA_SFLIGHT-CARRID.
    WRITE:/ SCARR-CARRNAME, WA_SFLIGHT-CURRENCY, WA_SFLIGHT-SALES, P_CURR, WA_SFLIGHT-CONVCURR.
  ENDLOOP.
